// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FilterResin struct {
	Name *string   `json:"name"`
	Desc *string   `json:"desc"`
	Tag  *InputTag `json:"tag"`
}

type InputFirm struct {
	Name string `json:"name"`
	Site string `json:"site"`
}

type InputPrinter struct {
	Name   string `json:"name"`
	FirmID string `json:"firmID"`
}

type InputResin struct {
	Name string      `json:"name"`
	Desc string      `json:"desc"`
	Tags []*InputTag `json:"tags"`
}

type InputTag struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type InputType struct {
	Name string `json:"name"`
	Desc string `json:"desc"`
}

type Options struct {
	Limit *int    `json:"limit"`
	Skip  *int    `json:"skip"`
	Order *string `json:"order"`
}
